export { default as Home } from "./home"
export { default as Activity } from "./activity"
export { default as Forum } from "./forum"
export { default as Profile } from "./profile"
export { default as Discussion } from "./discussion"